name: PR Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pr-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # =============================================== check changes ====================================================
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fail if the PR is a draft
        if: github.event_name == 'pull_request' && github.event.pull_request.draft == true
        run: |
          echo "This pull request is a draft. Failing the workflow."
          exit 1

      - name: Detect file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            main_package:
              - "python/**"

  # =============================================== primary ====================================================
  stage-a-test-1:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: 1-gpu-runner
    env:
      RUNNER_LABELS: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        timeout-minutes: 10
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run test
        timeout-minutes: 10
        run: |
          cd test/
          python3 run_suite.py --hw cuda --suite stage-a-test-1 --continue-on-error

  stage-b-test-small-1-gpu:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: 1-gpu-runner
    env:
      RUNNER_LABELS: 1-gpu-runner
    strategy:
      fail-fast: false
      matrix:
        partition: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        timeout-minutes: 10
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run test
        timeout-minutes: 30
        run: |
          cd test/
          python3 run_suite.py --hw cuda --suite stage-b-test-small-1-gpu --auto-partition-id ${{ matrix.partition }} --auto-partition-size ${{ strategy.job-total }} --continue-on-error

  stage-b-test-large-1-gpu:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: 1-gpu-runner
    env:
      RUNNER_LABELS: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        timeout-minutes: 10
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run test
        timeout-minutes: 30
        run: |
          cd test/
          python3 run_suite.py --hw cuda --suite stage-b-test-large-1-gpu --continue-on-error

  stage-b-test-large-2-gpu:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: 2-gpu-runner
    env:
      RUNNER_LABELS: 2-gpu-runner
    strategy:
      fail-fast: false
      matrix:
        partition: [0, 1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        timeout-minutes: 10
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run test
        timeout-minutes: 30
        run: |
          cd test/
          python3 run_suite.py --hw cuda --suite stage-b-test-large-2-gpu --auto-partition-id ${{ matrix.partition }} --auto-partition-size ${{ strategy.job-total }} --skip-file registered/disaggregation/test_disaggregation_basic.py --continue-on-error

  # add it back when 4-GPU H100 runners are available
  # stage-c-test-large-4-gpu:
  #   needs: [check-changes]
  #   if: always() && !failure() && !cancelled()
  #   runs-on: 4-gpu-h100
  #   env:
  #     RUNNER_LABELS: 4-gpu-h100
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install dependencies
  #       timeout-minutes: 10
  #       run: |
  #         bash scripts/ci/ci_install_dependency.sh

  #     - name: Run test
  #       timeout-minutes: 30
  #       run: |
  #         cd test/
  #         python3 run_suite.py --hw cuda --suite stage-c-test-large-4-gpu --continue-on-error

  performance-test-1-gpu-part-1:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Benchmark single latency
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_one_batch.TestBenchOneBatch.test_bs1_small
          python3 -m unittest test_bench_one_batch.TestBenchOneBatch.test_bs1_default

      - name: Benchmark online latency
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_online_latency_default

      - name: Benchmark offline throughput
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_offline_throughput_default

      - name: Benchmark offline throughput (Non-streaming, small batch size)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_offline_throughput_non_stream_small_batch_size

      - name: Benchmark online latency (EAGLE)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_online_latency_eagle

      - name: Benchmark online latency (LoRA)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_lora_online_latency
          python3 -m unittest test_bench_serving.TestBenchServing.test_lora_online_latency_with_concurrent_adapter_updates

  performance-test-1-gpu-part-2:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Benchmark offline throughput (w/o RadixAttention)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_offline_throughput_without_radix_cache

      - name: Benchmark offline throughput (w/ Triton)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_offline_throughput_with_triton_attention_backend

      - name: Benchmark offline throughput (w/ FP8)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_offline_throughput_default_fp8

      - name: Benchmark VLM offline throughput
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_vlm_offline_throughput

      - name: Benchmark VLM online latency
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_vlm_online_latency

  performance-test-1-gpu-part-3:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: 1-gpu-runner
    env:
      RUNNER_LABELS: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        timeout-minutes: 10
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Benchmark Scores online latency and throughput
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_score_api_latency_throughput

      - name: Benchmark Scores online latency and throughput (batch size scaling)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_score_api_batch_scaling

      - name: Benchmark Embeddings online latency and throughput
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_embeddings_api_latency_throughput

      - name: Benchmark Embeddings online latency and throughput (batch size scaling)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_embeddings_api_batch_scaling

  performance-test-2-gpu:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Benchmark single latency (TP=2)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_one_batch.TestBenchOneBatch.test_moe_tp2_bs1

      - name: Benchmark single latency + torch.compile (TP=2)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_one_batch.TestBenchOneBatch.test_torch_compile_tp2_bs1

      - name: Benchmark offline throughput (TP=2)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_moe_offline_throughput_default

      - name: Benchmark offline throughput (w/o RadixAttention) (TP=2)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_moe_offline_throughput_without_radix_cache

      - name: Benchmark offline PP decode throughput (PP=2)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_pp_offline_throughput_default_decode

      - name: Benchmark offline PP prefill throughput (PP=2)
        timeout-minutes: 10
        run: |
          cd test/srt
          python3 -m unittest test_bench_serving.TestBenchServing.test_pp_long_context_prefill

  accuracy-test-1-gpu:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh
          git clone https://github.com/merrymercy/human-eval.git
          cd human-eval
          pip install -e .

      - name: Evaluate accuracy
        timeout-minutes: 20
        run: |
          cd test/srt
          python3 test_eval_accuracy_large.py

  accuracy-test-2-gpu:
    needs: [check-changes, accuracy-test-1-gpu]
    if: always() && !failure() && !cancelled()
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh
          git clone https://github.com/merrymercy/human-eval.git
          cd human-eval
          pip install -e .

      - name: Evaluate accuracy (TP=2)
        timeout-minutes: 20
        run: |
          cd test/srt
          python3  -m sglang.test.ci.run_with_retry test_moe_eval_accuracy_large.py

  unit-test-backend-4-gpu-b200:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: b200-runner
    strategy:
      fail-fast: false
      matrix:
        part: [0, 1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          IS_BLACKWELL=1 bash scripts/ci/ci_install_dependency.sh

      - name: Run test
        timeout-minutes: 60
        run: |
          cd test/tgl
          IS_BLACKWELL=1 python3 run_suite.py --suite per-commit-4-gpu-b200 --auto-partition-id ${{ matrix.part }} --auto-partition-size ${{ strategy.job-total }} --timeout-per-file 3600

  unit-test-backend-4-gpu-b200-cursor:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: b200-runner
    strategy:
      fail-fast: false
      matrix:
        part: [0, 1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          IS_BLACKWELL=1 bash scripts/ci/ci_install_dependency.sh

      - name: Run test
        timeout-minutes: 60
        run: |
          cd test/tgl
          IS_BLACKWELL=1 SGLANG_TEST_MAX_RETRY=5 python3 run_suite.py --suite per-commit-4-gpu-b200-cursor --auto-partition-id ${{ matrix.part }} --auto-partition-size ${{ strategy.job-total }} --timeout-per-file 3600

  unit-test-backend-4-gpu-b200-cursor-phoenix:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: b200-runner
    strategy:
      fail-fast: false
      matrix:
        part: [0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          IS_BLACKWELL=1 bash scripts/ci/ci_install_dependency.sh

      - name: Run test
        timeout-minutes: 60
        run: |
          cd test/tgl
          IS_BLACKWELL=1 SGLANG_TEST_MAX_RETRY=5 python3 run_suite.py --suite per-commit-4-gpu-b200-cursor-phoenix --auto-partition-id ${{ matrix.part }} --auto-partition-size ${{ strategy.job-total }} --timeout-per-file 3600

  unit-test-backend-8-gpu-h200-tgl:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: h200-8gpu-runner
    strategy:
      fail-fast: false
      matrix:
        part: [0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run test
        timeout-minutes: 60
        run: |
          cd test/tgl
          python3 run_suite.py --suite per-commit-8-gpu-h200-tgl --auto-partition-id ${{ matrix.part }} --auto-partition-size ${{ strategy.job-total }} --timeout-per-file 3600

  per-commit-1-gpu-tgl:
    needs: [check-changes]
    if: always() && !failure() && !cancelled()
    runs-on: 1-gpu-runner
    env:
      RUNNER_LABELS: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        timeout-minutes: 10
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run test
        timeout-minutes: 20
        run: |
          cd test/tgl
          python3 run_suite.py --suite per-commit-1-gpu-tgl --continue-on-error

  pr-test-finish:
    needs: [
      check-changes,
      stage-a-test-1,
      stage-b-test-small-1-gpu,
      stage-b-test-large-1-gpu,
      stage-b-test-large-2-gpu,
      # stage-c-test-large-4-gpu,
      per-commit-1-gpu-tgl,
      performance-test-1-gpu-part-1,
      performance-test-1-gpu-part-2,
      performance-test-1-gpu-part-3,
      performance-test-2-gpu,
      accuracy-test-1-gpu,
      accuracy-test-2-gpu,
      unit-test-backend-4-gpu-b200,
      unit-test-backend-4-gpu-b200-cursor,
      unit-test-backend-8-gpu-h200-tgl
    ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check all dependent job statuses
        run: |
          # Convert the 'needs' context to a JSON string
          json_needs='${{ toJson(needs) }}'

          # Get a list of all job names from the JSON keys
          job_names=$(echo "$json_needs" | jq -r 'keys_unsorted[]')

          for job in $job_names; do
            # For each job, extract its result
            result=$(echo "$json_needs" | jq -r --arg j "$job" '.[$j].result')

            # Print the job name and its result
            echo "$job: $result"

            # Check for failure or cancellation and exit if found
            if [[ "$result" == "failure" || "$result" == "cancelled" ]]; then
              echo "The above jobs failed."
              exit 1
            fi
          done

          # If the loop completes, all jobs were successful
          echo "All jobs completed successfully"
          exit 0
